### ISSUE TITLE
cant receive file from client

### ISSUE THREAD

**Issue by bklol** [Nolo001-Aha/SourceMod-ReBanner#11]
os : debian

FileNet_RequestFile is never trigger a callback when plugin call RequestFile
and it give this error in console
![QQ截图20230424182009](https://user-images.githubusercontent.com/54763946/233969846-b0042eba-cab8-45e5-84f8-6f381aec893e.png)

**Comment by Nolo001-Aha** [comment]
Hello!

TF2 or CS:GO?

**Comment by Nolo001-Aha** [comment]
I'm blind, this is definitely CS:GO according to your console screenshot.

The issue you're facing should've been fixed in the latest commits, please download both File Network and Re-Banner from their master branches, compile and test.
This was solved in #7, you might want to refer to that Issue (scroll down closer to the bottom).
