### ISSUE TITLE
about sv_allowupload in csgo

### ISSUE THREAD

**Issue by bklol** [Nolo001-Aha/SourceMod-ReBanner#5]
hello! even server convar sv_allowupload is set to 1, but if the client itself set sv_allowupload to 0, the FileNet_SendFile callback will return sucess but it acturally not download the file, sence sv_allowupload Default Value is 0 on csgo client ,i guess maybe we should check client convar value too or just kick the client to force them change their convar value?

- server convar: ![server](https://user-images.githubusercontent.com/54763946/233643777-e4f39c37-bd79-47a9-a95a-2b6be536334f.png)
- about client :
![client](https://user-images.githubusercontent.com/54763946/233643784-70f20c71-5446-4279-b03a-a14e18cc9262.png)

**Comment by MickaNoob** [comment]
A have the same problem...

**Comment by Nolo001-Aha** [comment]
Hello!

Next release of Re-Banner will be able to work around client sv_allowupload being set to 0 in CSGO, instead I'm injecting into FastDownloads.

It's in testing phase right now, but everything seems to be working.

I'll drop a message here when it's public.

**Comment by Nolo001-Aha** [comment]
Hello yet again;

I pushed the new version to the main branch. It should work in CS:GO without relying solely on sv_allowupload.
Please compile and install that version.

Before use, PLEASE read the wiki page - it describes the new installation process and requirements in detail. 1.3 needs a FastDownloads server configured.
https://github.com/Nolo001-Aha/SourceMod-ReBanner/wiki

Important: It is highly recommended to drop the old database and create a new one due to changes in fingerprint length.
